"""add role to user

Revision ID: 61a596db25a5
Revises: 61523c94862c
Create Date: 2025-04-10 15:36:10.136959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a596db25a5'
down_revision: Union[str, None] = '61523c94862c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum('admin', 'user', name='role')
    role_enum.create(op.get_bind())
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'user', name='role'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum(name='role').drop(op.get_bind())
    # ### end Alembic commands ###
